Ajout de verif nom

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,7 +34,9 @@ jobs:
           sudo apt-get update && sudo apt-get install -y curl
           serve -s build -l 3000  | grep -q "Hello world! - Haya Aouate"; then
               echo "Test passed!"
-              break
+          else
+              echo "Test failed!"
+              exit 1
           fi
           sleep 10
           STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000)
